### ISSUE TITLE
Update link active color

### ISSUE THREAD

**Issue by evoeges** [GSA-TTS/federal-website-standards#159]
Link color on active is currently red. Should match USWDS active link color (#005ea2).

**Comment by michelle-rago** [comment]
@evoeges Can you post a screenshot of this? I'm not seeing the red. 😄

**Comment by caleywoods** [comment]
Also not seeing any red. We're also not setting any override colors for links that I can see in our CSS files either.

**Comment by evoeges** [comment]
Screen recording here:

https://github.com/user-attachments/assets/e407b3fc-389b-45bd-9607-825dcf0acb79

I'm using chrome on a macbook FYI.
