### ISSUE TITLE
Add DAP code to site

### ISSUE THREAD

**Issue by michelle-rago** [GSA-TTS/federal-website-standards#161]
We'll follow Digital.gov's agency/sub-agency model.

```

<script
--
  | async
  | type="text/javascript"
  | id="_fed_an_ua_tag"
  | src="https://dap.digitalgov.gov/Universal-Federated-Analytics-Min.js?agency=GSA&subagency=TTS"
  | ></script>


```

**Comment by rphillippi** [comment]
I've confirmed with Emily and Jacob that the site will only have DAP.

**Comment by caleywoods** [comment]
[This commit](https://github.com/GSA-TTS/federal-website-standards/commit/b48cd1bcffbb2bcbc54ba37e1cb7e7c2d5c39c70) by @michelle-rago takes care of this. It makes use of the 11ty templates built-in support for enabling DAP.
