### ISSUE TITLE
Generate a sitemap that can be automatically updated

### ISSUE THREAD

**Issue by michelle-rago** [GSA-TTS/federal-website-standards#166]

**Comment by caleywoods** [comment]
Right now our sitemap should be generated automatically when the Eleventy build process picks up the [sitemap template](https://github.com/GSA-TTS/federal-website-standards/blob/main/sitemap.xml.njk). This is a nunjucks template that creates an XML file filled with entries that represent all of the pages in our Eleventy collections.

**Comment by caleywoods** [comment]
@michelle-rago Do you think there's more to do here based on my comment above?

**Comment by michelle-rago** [comment]
> @michelle-rago Do you think there's more to do here based on my comment above?

Nope. I think this is good.
