### ISSUE TITLE
Update website margins

### ISSUE THREAD

**Issue by evoeges** [GSA-TTS/federal-website-standards#169]
Change desktop website margins to match the default margins used by [digital.gov](digital.gov). 

Hopefully a simple update from grid-container to grid-container-desktop.

[Rough mockup](https://drive.google.com/drive/folders/1-Fll_xRL8QlDYVKS75VBaecCr2UrZ7it
)

**Comment by michelle-rago** [comment]
Related issue https://github.com/18F/guides/issues/207

**Comment by caleywoods** [comment]
@michelle-rago This one is a little bit outside my wheelhouse. It would be faster for a front-end person to tackle. I'm happy to spend some time on it but it would be one of the last things I do since I think I can tackle a lot of the other issues remaining faster.
