### ISSUE TITLE
Add step indicator to standards pages and the about page

### ISSUE THREAD

**Issue by evoeges** [GSA-TTS/federal-website-standards#170]
Update status tags to be step indicators. We will use [the default USWDS component](https://designsystem.digital.gov/components/step-indicator/) for this. The three stages are: research, draft, standard. 

Initial tasks:

- [x] Research examples from other design systems / standards. [Example from california design system](https://designsystem.webstandards.ca.gov/components/page-feedback/readme/). 
- [x] Rough mockup of step indicator [Mockups here](https://drive.google.com/drive/folders/1-Fll_xRL8QlDYVKS75VBaecCr2UrZ7it) Note: mockups have old margins
- [ ] Add explanatory text for each phase to the step indicator
Research: This potential standard is being researched with the public and with federal agency staff.
Draft: The text of this potential standard has been drafted and is being shared with federal agencies and other stakeholders.
Pending: This will become a standard after a period of time. Agencies should plan to implement this standard.
Standard: Federal agencies are required to comply with this standard.
- [ ] Implement designs

**Comment by michelle-rago** [comment]
@caleywoods - @rphillippi and I talked about moving the status field / step indicator to below the H1 and above the Standard field. We don't have to do this now, but I wanted to flag it in case that impacts how you might build this. (cc: @evoeges)

**Comment by michelle-rago** [comment]
@caleywoods It should be "Standard."

- Research: This potential standard is being researched with the public and with federal agency staff.
- Draft: The text of this potential standard has been drafted and is being shared with federal agencies and other stakeholders.
- Pending: This will become a standard after a period of time. Agencies should plan to implement this standard.
- Standard: Federal agencies are required to comply with this standard.
