### ISSUE TITLE
Replace static images with actual components

### ISSUE THREAD

**Issue by evoeges** [GSA-TTS/federal-website-standards#171]
Currently state: standards that have an associated USWDS component display a static image of the component. [Banner example](https://federalist-142078a8-f654-4daa-8f73-db9770b3ec7a.sites.pages.cloud.gov/site/gsa-tts/federal-website-standards/standards/banner/). 

Future state: standards that have an associated USWDS component should display the actual component, in the same way that USWDS does. [Banner example](https://designsystem.digital.gov/components/banner/).

**Comment by michelle-rago** [comment]
@evoeges @caleywoods FYI I moved the image of the banner to the Example section of the banner standard page.
