### ISSUE TITLE
Match cards borders to default USWDS card component

### ISSUE THREAD

**Issue by evoeges** [GSA-TTS/federal-website-standards#173]
Current state: [Standard preview cards](https://federalist-142078a8-f654-4daa-8f73-db9770b3ec7a.sites.pages.cloud.gov/site/gsa-tts/federal-website-standards/standards/) have a different border stroke width and color from USWDS card defaults. They are also not a standardized height and bottom edges have a ragged appearance across a row. 

Future state: Update card borders to match [USWDS cards](https://designsystem.digital.gov/components/card/). Standardize height so that all cards in a row fill the same amount of space. 

[Rough mockups](https://drive.google.com/drive/folders/1-Fll_xRL8QlDYVKS75VBaecCr2UrZ7it)

**Comment by caleywoods** [comment]
The current layout is using USWDS [collection component](https://designsystem.digital.gov/components/collection/). Discussed with @evoeges and I'm going to change the layout to use the USWDS [card component](https://designsystem.digital.gov/components/card/) instead.
